//
//  RealtimeFeedHeader.swift
//  LocomoSwift
//
//  Metadata included in every GTFS Realtime FeedMessage.
//

import Foundation

public struct RealtimeFeedHeader: Hashable, Sendable {

    /// Version of the GTFS Realtime spec that this feed conforms to,
    /// e.g. `"2.0"`. Always present in well-formed feeds.
    public let gtfsRealtimeVersion: String

    /// Whether the fetch is a full snapshot (`.fullDataset`) or a
    /// differential update on top of a previous fetch (`.differential`).
    public let incrementality: Incrementality

    /// Moment when the feed was generated by the producer.
    public let timestamp: Date?

    /// Matches `feed_info.feed_version` from the underlying static GTFS feed.
    /// Useful to detect when consumers should re-download the static feed.
    public let feedVersion: String?

    public init(
        gtfsRealtimeVersion: String,
        incrementality: Incrementality,
        timestamp: Date? = nil,
        feedVersion: String? = nil
    ) {
        self.gtfsRealtimeVersion = gtfsRealtimeVersion
        self.incrementality = incrementality
        self.timestamp = timestamp
        self.feedVersion = feedVersion
    }
}
